export const calendarData = [
  { day: 1, status: "present" },
  { day: 2, status: "present" },
  { day: 3, status: "present" },
  { day: 4, status: "weekend" },
  { day: 5, status: "weekend" },
  { day: 6, status: "present" },
  { day: 7, status: "late" },
  { day: 8, status: "present" },
  { day: 9, status: "present" },
  { day: 10, status: "present" },
  { day: 11, status: "weekend" },
  { day: 12, status: "weekend" },
  { day: 13, status: "present" },
  { day: 14, status: "present" },
  { day: 15, status: "present" },
  { day: 16, status: "leave" },
  { day: 17, status: "leave" },
  { day: 18, status: "weekend" },
  { day: 19, status: "weekend" },
  { day: 20, status: "present" },
  { day: 21, status: "present" },
  { day: 22, status: "absent" },
  { day: 23, status: "present" },
  { day: 24, status: "present" },
  { day: 25, status: "weekend" },
  { day: 26, status: "weekend" },
  { day: 27, status: "present" },
  { day: 28, status: "present" },
  { day: 29, status: "present" },
  { day: 30, status: "present" },
  { day: 31, status: "weekend" },
];

export const attendanceLog = [
  {
    date: "Mon, Jul 21",
    checkin: "08:47",
    checkout: "17:15",
    hours: 7.5,
    breakDuration: "58 min",
    overtime: 0,
    status: "present",
    notes: "",
  },
  {
    date: "Mon, Jul 20",
    checkin: "08:32",
    checkout: "18:01",
    hours: 8.9,
    breakDuration: "45 min",
    overtime: 0.9,
    status: "present",
    notes: "",
  },
  {
    date: "Thu, Jul 17",
    checkin: "—",
    checkout: "—",
    hours: 0,
    breakDuration: "—",
    overtime: 0,
    status: "leave",
    notes: "Annual Leave",
  },
  {
    date: "Wed, Jul 16",
    checkin: "—",
    checkout: "—",
    hours: 0,
    breakDuration: "—",
    overtime: 0,
    status: "leave",
    notes: "Annual Leave",
  },
  {
    date: "Tue, Jul 15",
    checkin: "08:28",
    checkout: "18:28",
    hours: 9.5,
    breakDuration: "35 min",
    overtime: 1.5,
    status: "present",
    notes: "Q3 planning",
  },
  {
    date: "Mon, Jul 14",
    checkin: "08:41",
    checkout: "17:52",
    hours: 8.7,
    breakDuration: "42 min",
    overtime: 0.7,
    status: "present",
    notes: "",
  },
  {
    date: "Mon, Jul 13",
    checkin: "08:38",
    checkout: "17:41",
    hours: 8.3,
    breakDuration: "50 min",
    overtime: 0.3,
    status: "present",
    notes: "",
  },
  {
    date: "Thu, Jul 10",
    checkin: "08:30",
    checkout: "17:30",
    hours: 9.0,
    breakDuration: "30 min",
    overtime: 1.0,
    status: "present",
    notes: "",
  },
  {
    date: "Wed, Jul 9",
    checkin: "08:44",
    checkout: "17:50",
    hours: 8.6,
    breakDuration: "40 min",
    overtime: 0.6,
    status: "present",
    notes: "",
  },
  {
    date: "Tue, Jul 8",
    checkin: "09:05",
    checkout: "17:55",
    hours: 7.9,
    breakDuration: "55 min",
    overtime: 0,
    status: "present",
    notes: "",
  },
  {
    date: "Mon, Jul 7",
    checkin: "09:18",
    checkout: "18:00",
    hours: 7.7,
    breakDuration: "45 min",
    overtime: 0,
    status: "late",
    notes: "Traffic delay",
  },
  {
    date: "Mon, Jul 6",
    checkin: "08:35",
    checkout: "18:15",
    hours: 8.8,
    breakDuration: "42 min",
    overtime: 0.8,
    status: "present",
    notes: "",
  },
  {
    date: "Thu, Jul 3",
    checkin: "08:29",
    checkout: "17:20",
    hours: 8.0,
    breakDuration: "51 min",
    overtime: 0,
    status: "present",
    notes: "",
  },
  {
    date: "Wed, Jul 2",
    checkin: "08:33",
    checkout: "17:45",
    hours: 8.2,
    breakDuration: "45 min",
    overtime: 0.2,
    status: "present",
    notes: "",
  },
  {
    date: "Tue, Jul 1",
    checkin: "08:22",
    checkout: "18:30",
    hours: 9.4,
    breakDuration: "38 min",
    overtime: 1.4,
    status: "present",
    notes: "Month kickoff",
  },
];
