export const badges = [
  {
    id: "perfect",
    icon: "🏆",
    label: "Perfect Attendance",
    desc: "Jun 2026",
    earned: true,
    color: "#f59e0b",
  },
  {
    id: "streak30",
    icon: "🔥",
    label: "30-Day Streak",
    desc: "Earned May 2026",
    earned: true,
    color: "#ef4444",
  },
  {
    id: "earlybird",
    icon: "🌅",
    label: "Early Bird",
    desc: "Avg check-in before 8:45",
    earned: true,
    color: "#22d3ee",
  },
  {
    id: "consistent",
    icon: "⚡",
    label: "Consistency Champion",
    desc: "90%+ attendance 3 months",
    earned: true,
    color: "#8b5cf6",
  },
  {
    id: "overtime",
    icon: "💪",
    label: "Overtime Star",
    desc: "20+ overtime hrs/month",
    earned: false,
    color: "#6366f1",
  },
  {
    id: "focus",
    icon: "🎯",
    label: "Focus Master",
    desc: "Productivity > 95% for 2 wks",
    earned: false,
    color: "#10b981",
  },
];
